version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
     - ./server:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
    depends_on:
      - server
